name: Deploy Audio Demo to GitHub Pages

on:
  push:
    branches:
      - main # or your default branch

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: cd examples/audio-demo && npm install

      - name: Build
        run: cd examples/audio-demo && npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: examples/audio-demo/dist
          branch: gh-pages 